### ISSUE TITLE
Store addon config for project.

### ISSUE THREAD

**Issue by elmopl** [elmopl/ktba#5]
Makes it easier to use when you reload project file you don't have to set up everything.

**Comment by mond-cz** [comment]
Thanks, if this is possible -would be nice. For me It would be a big benefit just if blender will remember config for time that blender app is open. After quit and reopen app it become restore to default values. Or probably if blender can remember instances, since I had "N" cores, so I don't have to specify for each new blend?

**Comment by elmopl** [comment]
Now you should be able to set number of parallel instances in addon settings (in User Preferences).
This will be your default value each time yous start Blender.

As you are unlikely to keep on changing this one I think this should work fine (you can still override it for current Blender session, but to save it you have to save User Preferences).

The rest of options are saved on per scene basis.

**Comment by tin2tin** [comment]
I don't know if you'll see this comment in a closed issue, but it would be nice if the ffmpeg path was stored in the config too. :-)
